language: csharp
solution: ImsGlobal.Caliper.sln
install:
  - nuget restore ImsGlobal.Caliper.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ImsGlobal.Caliper.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./test/ImsGlobal.Caliper.Tests/bin/Release/ImsGlobal.Caliper.Tests.dll
